### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by matthijsramlab** [okta/samples-python-flask#17]
When I try to connect to login I get the following message:

Unable to connect to the server. Please check your network connection.

In the browser console I got the following errors: 

1. Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://%7B%7Bhttps//dev-933489.okta.com%7D%7D/api/v1/authn

2. name: "UNSUPPORTED_BROWSER_ERROR"
message: "There was an error sending the request - have you enabled CORS?"

**Comment by av1m** [comment]
Hello, for the second error check under Admin → Security → API → Trusted Origins.
I redirect you to the [documentation](https://developer.okta.com/docs/guides/enable-cors/overview/)

**Comment by matthijsramlab** [comment]
Thanks! That was indeed the problem
