### ISSUE TITLE
Setup Self Registration

### ISSUE THREAD

**Issue by matthijsramlab** [okta/samples-python-flask#18]
Is it possible to add self registration to the examples? If not, could someone provide an simple example.

**Comment by serhiibuniak-okta** [comment]
Hi @matthijsramlab , sorry for a late response. The samples here are a jumping off point to show you the basics of authentication using python and flask so we don't go into anything further yet around all the use cases. But I can help you with a little guidance. If I understand you correctly, you're looking for this https://developer.okta.com/docs/reference/api/users/#create-user ?
In this case, you should have some "sign-up" route with accessing this endpoint via our sdk https://github.com/okta/okta-sdk-python#create-a-user:
```py
# pseudo-code example

from okta.client import Client

@app.route("/sign_up")
def register_user(params):
    client = Client()
    client.create_user(params)
    # process response, return response or error
```
Is this helpful?

**Comment by serhiibuniak-okta** [comment]
I'm going to close this issue as it seems to be stalled. @matthijsramlab feel free to open a new issue if you need some assistance. Thanks for using OKTA!
