### ISSUE TITLE
getting bad request when running the okat-hosted-login example

### ISSUE THREAD

**Issue by royt-via** [okta/samples-python-flask#19]
Hi,
I ran the okat-hosted-login example (after setting an application on okta with the same `redirect_uri` as the `Login redirect URI`).
After clicking on `Login` I get a bad request page with the message `The 'redirect_uri' parameter must be an absolute URI that is whitelisted in the client app settings ` -
![image](https://user-images.githubusercontent.com/57411950/75490624-7ca48a00-5982-11ea-8afb-26d648b069c9.png)

I already double checked my api keys are correct and that the `redirect_uri` matches the `Login redirect URI`.

Would appreciate your help.

**Comment by mraible** [comment]
If you look in your browser's address bar when this happens, you can copy/paste the redirect_uri parameter and compare it to your login redirect URIs in your app. If you add the one it's trying to go to, it'll usually work.
