### ISSUE TITLE
Cannot install requirements due to MarkupSafe

### ISSUE THREAD

**Issue by mwangersjo** [okta/samples-python-flask#24]
Running pip install in a clean Python 3.7 env fails.

Reproducible example: Add this docker file to samples-python-flask and build
```
FROM python:3.7
ADD requirements.txt .

RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt
```
The problem has been discussed in the MarkupSafe repo (https://github.com/pallets/markupsafe/issues/57) and is solved by bumping the version of markup to 1.1.1 as described in this comment: https://github.com/pallets/markupsafe/issues/57#issuecomment-597105876

**Comment by bretterer** [comment]
Thanks for the info and bug report here.  I will get this on our list to address.

**Comment by bretterer** [comment]
Internal Ref: OKTA-321989
