### ISSUE TITLE
Line 54 fails with str error in Python 2.7 

### ISSUE THREAD

**Issue by eafigbo** [okta/samples-python-flask#34]
https://github.com/okta/samples-python-flask/blob/71341a5497f622635aea03d0f3d7afa5a282c98b/custom-login/main.py#L54

This line fails in Python 2.7 with error:
str() takes at most 1 argument (2 given) 

Had to change to:
    return str(base64.b64encode(json.dumps(data).encode('utf-8'))).encode('utf-8')
Worth correcting or specifying that the sample is for Python 3

**Comment by serhiibuniak-okta** [comment]
@eafigbo Thank you for posting this issue. Yes, need to mention that all samples require Python 3.6+.
Will update README soon. Is there anything else which is worth to specify in README?

**Comment by serhiibuniak-okta** [comment]
@eafigbo I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem still exists.
