### ISSUE TITLE
flask_oidc package is not well maintained

### ISSUE THREAD

**Issue by flying-falcon** [okta/samples-python-flask#4]
Hi,
flask_oidc package is not well maintained(last release was on last April). Could you make this to the certified version from openid https://github.com/OpenIDC/pyoidc  https://openid.net/developers/certified/

**Comment by serhiibuniak-okta** [comment]
Hi @flying-falcon. Thank you for posting this issue. Although, it is very old, but we've taken it into account and found another solution to get rid of flask-oidc library: https://github.com/okta/samples-python-flask/pull/41

**Comment by serhiibuniak-okta** [comment]
@flying-falcon Finally, everything is updated, I'm closing this issue as resolved.
