### ISSUE TITLE
Resource-Server readme says client-id from SPA but it should be from Web App

### ISSUE THREAD

**Issue by ncapdevi** [okta/samples-python-flask#45]
https://github.com/okta/samples-python-flask/blob/master/resource-server/README.md 

The readme for the resource-server says that you need the client-id from the SPA, but this is incorrect. You need the client-id and client-secret (SPA doesn't have a client-secret) from a web application. This is adding to the confusion that was identified in this comment. https://github.com/okta/samples-python-flask/issues/31#issuecomment-727259060

**Comment by bryanapellanes-okta** [comment]
@ncapdevi,
Thanks for letting us know.  I'll bring this to the attention of our python developers for further review. 

Thanks for using Okta!

**Comment by serhiibuniak-okta** [comment]
@ncapdevi Thanks for posting this issue. I'll take care of it. Will post updates here.

**Comment by serhiibuniak-okta** [comment]
@ncapdevi README updated. I'm closing this issue as resolved. Feel free to reopen this issue or create a new one in case of any questions.
