### ISSUE TITLE
Typo in setup.py, usr is spelled 'suer'

### ISSUE THREAD

**Issue by DanielJoyce** [okta/samples-python-flask#51]
First line

#!/suer/bin/env python

**Comment by DanielJoyce** [comment]
Looks like no one actually tested this example.

**Comment by DanielJoyce** [comment]
Apparently 'suer' is a utility I have never heard of before, also not installed by default

**Comment by serhiibuniak-okta** [comment]
@DanielJoyce  Thanks for posting this issue. Usually, first (shebang) line is interpreted when script is being executed directly. When we run it like `python setup.py`, this line is ignored. Anyway, we will fix this typo.

**Comment by DanielJoyce** [comment]
I usually make python scripts executable and use hashbang.

**Comment by serhiibuniak-okta** [comment]
I made a PR to fix this, once it is reviewed, I'll merge it https://github.com/okta/samples-python-flask/pull/53

**Comment by serhiibuniak-okta** [comment]
@DanielJoyce Merged, I'm closing this issue as resolved. Feel free to reopen this issue if your problem still exists.
