### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by DanielJoyce** [okta/samples-python-flask#52]
Well, I haven't gotten it to run yet, but probably needs to be moved to python 3

**Comment by serhiibuniak-okta** [comment]
@DanielJoyce Do you mean that you're using python 2.x? README says `Requires Python version 3.6.0 or higher.`
Post here if you need some help with "start and run" this samples.

**Comment by DanielJoyce** [comment]
I got it working. Seems to be python3. Setup.py in root refers to python 2.x

**Comment by serhiibuniak-okta** [comment]
So, how did you manage to run it? Could you please share this information here just in case for the similar issues in future?

**Comment by serhiibuniak-okta** [comment]
@DanielJoyce I'm closing this issue as resolved. Feel free to add any information you find useful.
