### ISSUE TITLE
Using flask resource-server example with flask okta-hosted-login example

### ISSUE THREAD

**Issue by foragerr** [okta/samples-python-flask#58]
The resource-server README says

> Once logged in, you can navigate to the "Messages" page to see the interaction with the resource server.

However, the flask login examples in this repo do not seem to have a `/messages` endpoint. The resource-server works fine with the js-angular frontend example. 

Are `okta-hosted-login` and `resource-server` examples in this repo meant to be used as stand-alone examples and not together?

**Comment by serhiibuniak-okta** [comment]
@foragerr Yes, `okta-hosted-login`, `custom-login` and `resource-server` are stand-alone examples to demo different features, see README https://github.com/okta/samples-python-flask

**Comment by foragerr** [comment]
Thank you.
