### ISSUE TITLE
Getting a KeyError: 'client_id' when running the okta-hosted-login

### ISSUE THREAD

**Issue by gaelletjat** [okta/samples-python-flask#59]
Hello there,
I was able to successfully deploy okta-hosted-login and navigate to the application on my localhost. 
However, when I click on Login, I run into a KeyError issue.

```
query_params = {'client_id': config["client_id"],
KeyError: 'client_id'
```
I am not sure what I am missing. I did not change the code other than adding my details.
In the browser, the URL is 
`localhost:8080/login?`
Could you please help?

**Comment by gaelletjat** [comment]
This has been resolved

**Comment by gaelletjat** [comment]
I was able to track down the issue. I am now able to connect.
Thank you

**Comment by serhiibuniak-okta** [comment]
Hi @gaelletjat, was typing response, but now I see everything is working for you. Thanks for letting us know that everything is fine.

**Comment by gaelletjat** [comment]
Thank you @sergiishamrai-okta
