### ISSUE TITLE
KeyError: 'client_id'

### ISSUE THREAD

**Issue by BrookRemington** [okta/samples-python-flask#64]
I'm having the same problem described in issue #59. I can run the Okta Hosted Login example, but when I click on the login button, I get a KeyError.

**Comment by serhiibuniak-okta** [comment]
@BrookRemington Unfortunately, that issue is resolved by issuer without any information what was wrong and what was the fix. I guess, something was misconfigured. Could you please, provide more details?
First, you can do a simple check if config file is valid, cd to directory okta-hosted-login and check if there is no error:
```py
>>> from helpers import config
>>> config['client_id']
# should print "your client_id" here or raise a KeyError
```
If config file has the same format as described here https://github.com/okta/samples-python-flask/tree/master/okta-hosted-login#running-this-example and you use the latest source code, everything should be fine.

**Comment by BrookRemington** [comment]
Okay, I figured it out. The client_secrets.json file that was generated with the SDK doesn't quite match the required format. Once that's fixed, everything works great. Thanks.

**Comment by serhiibuniak-okta** [comment]
@BrookRemington Thank you for letting us know that everything is fine. Config differs, because we don't need SDK and complex configuration for these samples (samples are just a starting point/demo). Thus, we decided to simplify as much as possible.

**Comment by aevain** [comment]
Hi,
@BrookRemington: would mind telling me what you did exactly?
I've come accross the same issue and I don't see anything wrong with the format

Thanks

**Comment by BrookRemington** [comment]
@aevain the required format is:

{
  "auth_uri": "https://{yourOktaDomain}/oauth2/default/v1/authorize",
  "client_id": "{yourClientId}",
  "client_secret": "{yourClientSecret}",
  "redirect_uri": "http://localhost:8080/authorization-code/callback",
  "issuer": "https://{yourOktaDomain}/oauth2/default",
  "token_uri": "https://{yourOktaDomain}/oauth2/default/v1/token",
  "token_introspection_uri": "https://{yourOktaDomain}/oauth2/default/v1/introspect",
  "userinfo_uri": "https://{yourOktaDomain}/oauth2/default/v1/userinfo"
}

The SDK generates one that looks like this:

{"web": {
  "token_uri": "https://{yourOktaDomain}/oauth2/default/v1/token",
  "auth_uri": "https://{yourOktaDomain}/oauth2/default/v1/authorize",
  "client_secret": "{yourClientSecret}",
  "redirect_uris": ["http://localhost:8080/authorization-code/callback"],
  "issuer": "https://{yourOktaDomain}/oauth2/default",
  "client_id": "{yourClientId}"
}}

There are several differences: There are two key value pairs missing from the SDK code, token_introspection_uri and userinfo_uri. Also, the key redirect_uris should be be called redirect_uri (without an s at the end), and the value should not be in square brakets. Finally, delete the "web": part at the begining, along with the extra brakets.

**Comment by aevain** [comment]
thanks for your reply, eventually I managed to find the issue (took me a while though :) )
But it's good to have the confirmation
thanks again
